const documents=[
 {title:'Cuestionario impreso · Inglés',meta:'Documento escaneado · 26 páginas',tag:'FUENTE PRINCIPAL',short:'TEST',file:'Cuestionario impreso - Ingles.pdf',spanishTitle:'Cuestionario impreso · Español',spanishMeta:'Traducción de estudio · 26 hojas · 254 preguntas',spanishFile:'Cuestionario impreso - Espanol.pdf'},
 {title:'Commercial Driver Handbook',meta:'Inglés · edición 2019–2021 / archivo 2023 · 208 páginas',tag:'MANUAL COMERCIAL',short:'CDL',file:'DL-650-2019-2021-Aug-2023-passes-accessibility.pdf',spanishTitle:'Manual del Conductor Comercial',spanishMeta:'Español oficial DMV · 208 páginas',spanishFile:'Commercial-Driver-Handbook-Spanish-Official.pdf'},
 {title:"California Driver’s Handbook",meta:'Inglés · edición 2025 · 92 páginas',tag:'MANUAL GENERAL',short:'CA',file:'8-11-25-DL-600-R6-2025-WWW.pdf',spanishTitle:'Resumen del Manual del Automovilista',spanishMeta:'Español oficial DMV · edición 2025 · 68 páginas',spanishFile:'California-Driver-Handbook-2025-Spanish-Official.pdf'}
];
const questions=[
 {q:'You should try to park your vehicle so:',es:'Debe tratar de estacionar su vehículo de modo que:',a:['You can pull forward when you leave.','There is at least one curb next to your vehicle.','Your vehicle is protected by trees or some other overhang.'],correct:0,why:'Salir hacia adelante permite ver mejor el tráfico y evita una maniobra de reversa con puntos ciegos. Referencia: conducción segura y estacionamiento.'},
 {q:'Controlled braking:',es:'El frenado controlado:',a:['Involves locking the wheels for short periods of time.','Is used to keep a vehicle in a straight line when braking.','Should only be used with hydraulic brakes.'],correct:1,why:'El frenado controlado aplica los frenos con fuerza sin bloquear las ruedas, permitiendo conservar el control direccional. Referencia: Manual Comercial, Sección 2.'},
 {q:'CDL medical certificates must be renewed every:',es:'Los certificados médicos CDL deben renovarse cada:',a:['Year.','Two years.','Four years.'],correct:1,why:'El certificado médico comercial normalmente tiene una vigencia máxima de dos años, aunque un examinador puede emitirlo por menos tiempo. Referencia: Manual Comercial, Sección 1.'},
 {q:'You are stopped. You want to start driving uphill. You should:',es:'Está detenido. Quiere comenzar a conducir cuesta arriba. Debe:',a:['Partly engage the clutch and then release the parking brake.','Engage the clutch and accelerate quickly.','Keep the trailer brake hand valve applied until you reach 20 mph.'],correct:0,why:'Acoplar parcialmente el embrague antes de liberar el freno de estacionamiento ayuda a evitar que el vehículo ruede hacia atrás. Referencia: control básico del vehículo.'},
 {q:'Which of these is not proper use of vehicle lights?',es:'¿Cuál de estos no es un uso adecuado de las luces del vehículo?',a:['Turning on your headlights during the day when visibility is reduced.','Flashing your brake lights to warn someone behind you that you are slowing down.','Flashing your brake lights to stop someone tailgating.'],correct:2,why:'Las luces de freno pueden advertir una reducción de velocidad, pero usarlas para intentar controlar a quien sigue demasiado cerca no es una medida segura. Referencia: Manual Comercial, comunicación.'},
 {q:'Which of the following is not a type of retarder?',es:'¿Cuál de los siguientes no es un tipo de retardador?',a:['Electric.','Hydraulic.','Robotic.'],correct:2,why:'Los retardadores comerciales pueden ser eléctricos, hidráulicos o de motor; “robótico” no es un tipo de retardador. Referencia: Manual Comercial, control de velocidad.'},
 {q:'What is the first thing you should do if your brakes fail while driving downhill?',es:'¿Qué es lo primero que debe hacer si fallan los frenos mientras conduce cuesta abajo?',a:['Call or radio for help.','Try to use your parking brake to stop.','Get off the road as soon as possible.'],correct:2,why:'La prioridad es sacar el vehículo de la vía principal y buscar una ruta de escape o lugar seguro; pedir ayuda no detiene el vehículo. Referencia: emergencias de conducción.'},
 {q:'You are driving a 40 foot vehicle at 35 mph. The road is dry and visibility is good. What is the least amount of space you should keep in front of your vehicle to be safe?',es:'Conduce un vehículo de 40 pies a 35 mph. El camino está seco y la visibilidad es buena. ¿Cuál es el espacio mínimo que debe mantener delante para estar seguro?',a:['3 seconds.','4 seconds.','5 seconds.'],correct:1,why:'La regla usa al menos un segundo por cada diez pies de longitud cuando se conduce por debajo de 40 mph: 40 pies requieren cuatro segundos. Referencia: Manual Comercial, gestión del espacio.'},
 {q:'When you drive in the mountains, which of these does not affect your choice of gears?',es:'Al conducir en las montañas, ¿cuál de estos no afecta su elección de marchas?',a:['Weight of the load.','Tire tread type.','Length of the grade.'],correct:1,why:'La pendiente, su longitud y el peso influyen en la marcha segura; el tipo de dibujo de la llanta no determina la selección de marcha. Referencia: conducción en montaña.'},
 {q:'When you must stop on a one-way or divided highway, where should you place reflective triangles?',es:'Cuando debe detenerse en una carretera de un solo sentido o dividida, ¿dónde debe colocar los triángulos reflectantes?',a:['10 feet, 100 feet, and 500 feet toward approaching traffic.','10 feet, 100 feet, and 200 feet toward approaching traffic.','10 feet, 50 feet, and 100 feet toward approaching traffic.'],correct:1,why:'En una carretera dividida o de un solo sentido, los dispositivos se colocan a 10, 100 y 200 pies hacia el tráfico que se aproxima. Referencia: Manual Comercial, dispositivos de advertencia.'}
];
const state=JSON.parse(localStorage.getItem('rutaCdlProgress')||'{"answers":{},"checked":{}}');let current=0,currentDocument=0,currentDocLanguage='en';
let scanPage=1,scanZoom=75;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function markActivity(){const today=new Date().toISOString().slice(0,10),days=JSON.parse(localStorage.getItem('rutaCdlStudyDays')||'[]');if(!days.includes(today)){days.push(today);localStorage.setItem('rutaCdlStudyDays',JSON.stringify(days.slice(-365)))}}
function save(){markActivity();localStorage.setItem('rutaCdlProgress',JSON.stringify(state));updateStats()}
function renderDocuments(){const list=$('#documentList');list.innerHTML=documents.map((d,i)=>`<button class="doc-card ${i===0?'active':''}" data-doc="${i}"><span class="doc-thumb">${d.short}</span><span><b class="doc-tag">${d.tag}</b><strong>${d.title}</strong><small>${d.meta}</small>${d.spanishFile?'<em class="official-es">ESPAÑOL OFICIAL DISPONIBLE</em>':''}</span></button>`).join('');$$('[data-doc]').forEach(b=>b.onclick=()=>{currentDocLanguage='en';selectDocument(+b.dataset.doc)});selectDocument(0)}
function selectDocument(i){currentDocument=i;const d=documents[i],useSpanish=currentDocLanguage==='es'&&d.spanishFile,file=useSpanish?d.spanishFile:d.file;$$('[data-doc]').forEach((b,n)=>b.classList.toggle('active',n===i));$('#viewerTitle').textContent=useSpanish?d.spanishTitle:d.title;$('#viewerMeta').textContent=useSpanish?d.spanishMeta:d.meta;$('#pdfViewer').data=encodeURI(file);$('#openPdf').href=file;$('#downloadPdf').href=file;$('#fallbackPdf').href=file;$('#languageButton').innerHTML=`${useSpanish?'ES':'EN'} <span>↔</span> ${useSpanish?'EN':'ES'}`}
function renderQuestion(){const q=questions[current];$('#questionLabel').textContent=`PREGUNTA ${current+1} DE ${questions.length}`;$('#quizProgress').style.width=`${(current+1)*10}%`;$('#questionText').textContent=q.q;$('#questionTranslation').textContent=q.es;$('#questionTranslation').hidden=true;$('#translateToggle').textContent='Ver apoyo en español';$('#feedback').hidden=true;$('#answerList').innerHTML=q.a.map((a,i)=>`<button class="answer ${state.answers[current]==i?'selected':''} ${state.checked[current]?(i===q.correct?'correct':state.answers[current]===i?'wrong':''):''}" data-answer="${i}"><span>${'ABC'[i]}</span>${a}</button>`).join('');$$('[data-answer]').forEach(b=>b.onclick=()=>{if(state.checked[current])return;state.answers[current]=+b.dataset.answer;save();renderQuestion()});renderMap()}
function renderMap(){$('#questionMap').innerHTML=questions.map((_,i)=>`<button data-q="${i}" class="${i===current?'active':''} ${state.answers[i]!=null?'answered':''}">${i+1}</button>`).join('');$$('[data-q]').forEach(b=>b.onclick=()=>{current=+b.dataset.q;renderQuestion()})}
function checkAnswer(){if(state.answers[current]==null){$('#feedback').hidden=false;$('#feedback').textContent='Selecciona una respuesta antes de comprobar.';return}state.checked[current]=true;save();renderQuestion();const q=questions[current],ok=state.answers[current]===q.correct;$('#feedback').hidden=false;$('#feedback').innerHTML=`<strong>${ok?'Correcto.':'Respuesta incorrecta.'}</strong> ${q.why}`}
function updateStats(){
 const quizAnswered=Object.keys(state.answers).length,quizChecked=Object.keys(state.checked).length,quizCorrect=Object.keys(state.checked).filter(i=>state.answers[i]===questions[i].correct).length;
 const topics={general:{answered:0,correct:0},brakes:{answered:0,correct:0},passenger:{answered:0,correct:0}};let sourceAnswered=0,sourceChecked=0,sourceCorrect=0;
 if(typeof pageForms!=='undefined'&&typeof sourceAnswers!=='undefined')Object.entries(pageForms).forEach(([page,form])=>{const answers=sourceAnswers[`p${page}`]||{},topic=form.section.includes('Air Brake')?'brakes':form.section.includes('Passenger')?'passenger':'general';Object.entries(answers).forEach(([n,letter])=>{sourceAnswered++;if(form.key?.[n]){sourceChecked++;topics[topic].answered++;if(form.key[n]===letter){sourceCorrect++;topics[topic].correct++}}})});
 const answered=quizAnswered+sourceAnswered,checked=quizChecked+sourceChecked,correct=quizCorrect+sourceCorrect,accuracy=checked?Math.round(correct/checked*100):0;topics.general.answered+=quizChecked;topics.general.correct+=quizCorrect;
 $('#answeredStat').textContent=answered;$('#accuracyStat').textContent=checked?`${accuracy}%`:'—';
 [['general','#generalBar','#generalFill'],['brakes','#brakesBar','#brakesFill'],['passenger','#passengerBar','#passengerFill']].forEach(([topic,label,fill])=>{const t=topics[topic],value=t.answered?Math.round(t.correct/t.answered*100):0;$(label).textContent=`${value}%`;$(fill).style.width=`${value}%`});
 const completion=Math.min(100,Math.round(sourceAnswered/255*100));$('#heroPercent').textContent=`${completion}%`;$('.ring').style.background=`conic-gradient(var(--amber) 0 ${completion}%,#dfe5e7 ${completion}%)`;$('#heroAnswered').textContent=`${sourceAnswered}/255`;$('#heroProgressCopy').textContent=`${sourceAnswered} de 255 espacios respondidos.`;$('#heroProgressTitle').textContent=sourceAnswered===255?'Cuestionario completado':sourceAnswered?'Sigue donde lo dejaste':'Comienza cuando quieras';
 const studyDays=JSON.parse(localStorage.getItem('rutaCdlStudyDays')||'[]').sort(),daySet=new Set(studyDays);let streak=0,cursor=new Date();if(!daySet.has(cursor.toISOString().slice(0,10)))cursor.setDate(cursor.getDate()-1);while(daySet.has(cursor.toISOString().slice(0,10))){streak++;cursor.setDate(cursor.getDate()-1)}$('#streakStat').textContent=streak;
 if(quizChecked===questions.length)localStorage.setItem('rutaCdlBest',Math.max(quizCorrect,+localStorage.getItem('rutaCdlBest')||0));const history=JSON.parse(localStorage.getItem('rutaCdlExamHistory')||'[]'),bestExam=history.reduce((m,x)=>Math.max(m,x.percent||0),0),best=+localStorage.getItem('rutaCdlBest')||0;$('#bestScore').textContent=bestExam?`${bestExam}%`:best?`${best}/10`:'—';
 $('#examHistory').innerHTML=history.length?history.slice(0,6).map(attempt=>`<article class="history-attempt"><strong>${attempt.percent}%</strong><span>${attempt.score}/${attempt.size} correctas</span><small>${new Date(attempt.date).toLocaleDateString('es-US')}</small></article>`).join(''):'<p>Completa un examen personalizado para iniciar tu historial.</p>';
}
function showPractice(mode){$$('[data-practice]').forEach(b=>b.classList.toggle('active',b.dataset.practice===mode));$('#quizShell').hidden=mode!=='quiz';$('#matchShell').hidden=mode!=='match';$('#rapidShell').hidden=mode!=='rapid';$('#sourceExamShell').hidden=mode!=='source';$('#customExamShell').hidden=mode!=='custom';if(mode==='match')renderMatch();if(mode==='rapid')renderRapid();if(mode==='source')renderSourceExam();if(mode==='custom')renderExamBuilder()}
const pairs=[['Service brake','Freno de servicio'],['Parking brake','Freno de estacionamiento'],['Emergency brake','Freno de emergencia'],['Air pressure','Presión de aire'],['Slack adjuster','Ajustador de holgura'],['Brake chamber','Cámara de freno'],['Air compressor','Compresor de aire'],['Governor','Gobernador'],['Supply pressure gauge','Medidor de presión de suministro'],['Low air warning','Advertencia de baja presión'],['Spring brakes','Frenos de resorte'],['Brake fade','Desvanecimiento de frenos'],['Reflective triangles','Triángulos reflectantes'],['Stopping distance','Distancia de parada'],['Blind spot','Punto ciego'],['Standee line','Línea para pasajeros de pie'],['Emergency exit','Salida de emergencia'],['Railroad crossing','Cruce ferroviario']];let matchPick=null,matched=[];
function renderMatch(){const left=pairs.map((p,i)=>({text:p[0],id:i,side:'a'}));const right=[...pairs].reverse().map((p,ri)=>({text:p[1],id:pairs.length-1-ri,side:'b'}));$('#matchShell').innerHTML=`<div class="section-heading compact"><div><p class="eyebrow dark"><span></span> Relacionar</p><h2>Une cada concepto</h2><p>Selecciona un término en inglés y su equivalente en español.</p></div><strong>${matched.length}/${pairs.length}</strong></div><div class="match-grid">${[left,right].map(col=>`<div>${col.map(x=>`<button class="match-card ${matched.includes(x.id)?'matched':''}" data-pair="${x.id}" data-side="${x.side}">${x.text}</button>`).join('')}</div>`).join('')}</div>`;$$('[data-pair]').forEach(b=>b.onclick=()=>pickMatch(b))}
function pickMatch(b){if(matched.includes(+b.dataset.pair))return;if(!matchPick){matchPick=b;b.classList.add('selected');return}if(matchPick.dataset.side!==b.dataset.side&&matchPick.dataset.pair===b.dataset.pair){matched.push(+b.dataset.pair);matchPick=null;renderMatch()}else{matchPick.classList.remove('selected');matchPick=b;b.classList.add('selected')}}
let rapidTimer=null,rapidSeconds=60,rapidCorrect=0,rapidAnswered=0,rapidQuestion=0;
function renderRapid(){clearInterval(rapidTimer);$('#rapidShell').innerHTML=`<div class="rapid-card"><p class="eyebrow dark"><span></span> Reto relámpago</p><div class="timer">60</div><h2>¿Cuántas puedes responder en un minuto?</h2><p>Retroalimentación inmediata, orden aleatorio y resultado final.</p><button class="primary" id="startRapid">Empezar reto →</button></div>`;$('#startRapid').onclick=startRapid}
function startRapid(){rapidSeconds=60;rapidCorrect=0;rapidAnswered=0;rapidQuestion=Math.floor(Math.random()*questions.length);renderRapidQuestion();rapidTimer=setInterval(()=>{rapidSeconds--;const timer=$('#rapidTime');if(timer)timer.textContent=rapidSeconds;if(rapidSeconds<=0)finishRapid()},1000)}
function renderRapidQuestion(){const q=questions[rapidQuestion];$('#rapidShell').innerHTML=`<div class="rapid-live"><div class="rapid-live-head"><strong id="rapidTime">${rapidSeconds}</strong><span>${rapidCorrect} correctas · ${rapidAnswered} respondidas</span></div><small>RETO RELÁMPAGO</small><h3>${q.q}</h3><div class="scenario-options">${q.a.map((x,i)=>`<button data-rapid-answer="${i}">${x}</button>`).join('')}</div></div>`;$$('[data-rapid-answer]').forEach(b=>b.onclick=()=>{rapidAnswered++;if(+b.dataset.rapidAnswer===q.correct)rapidCorrect++;rapidQuestion=(rapidQuestion+1+Math.floor(Math.random()*(questions.length-1)))%questions.length;renderRapidQuestion()})}
function finishRapid(){clearInterval(rapidTimer);rapidTimer=null;$('#rapidShell').innerHTML=`<div class="rapid-card"><p class="eyebrow dark"><span></span> RETO COMPLETADO</p><div class="timer">${rapidCorrect}</div><h2>respuestas correctas</h2><p>${rapidAnswered} respondidas · ${rapidAnswered?Math.round(rapidCorrect/rapidAnswered*100):0}% de precisión</p><button class="primary" id="startRapid">Intentar de nuevo →</button></div>`;$('#startRapid').onclick=startRapid}
const cardDeck=[['Service brake','Freno de servicio','Applies and releases the brakes during normal driving.'],['Parking brake','Freno de estacionamiento','Holds the vehicle when parked.'],['Emergency brake','Freno de emergencia','Uses parts of the service and parking systems during a failure.'],['Brake chamber','Cámara de freno','Converts air pressure into mechanical force.'],['Slack adjuster','Ajustador de holgura','Connects the brake chamber pushrod to the brake mechanism.'],['Air compressor','Compresor de aire','Pumps air into the storage tanks.'],['Governor cut-out','Corte del gobernador','The point where the compressor stops pumping air.'],['Low air warning','Advertencia de baja presión','Must activate before pressure falls below the specified limit.'],['Standee line','Línea para pasajeros de pie','Riders must remain behind it while the bus is moving.'],['Reflective triangles','Triángulos reflectantes','Warning devices placed when a commercial vehicle is stopped.'],['GVWR','Clasificación de peso bruto vehicular','Manufacturer-specified loaded weight rating for a single vehicle.'],['Controlled braking','Frenado controlado','Braking hard without locking the wheels.']];let cardIndex=0,cardRevealed=false;const cardMastery=JSON.parse(localStorage.getItem('rutaCdlCardMastery')||'{}');
function renderCardDeck(){const c=cardDeck[cardIndex],known=Object.values(cardMastery).filter(Boolean).length;$('#academyStage').innerHTML=`<div class="activity-panel card-deck-panel"><div class="deck-progress"><span>TARJETA ${cardIndex+1} / ${cardDeck.length}</span><strong>${known} dominadas</strong></div><button class="study-flashcard ${cardRevealed?'revealed':''}" id="studyFlashcard"><div class="card-front"><small>INGLÉS</small><h3>${c[0]}</h3><span>Toca para revelar</span></div><div class="card-back"><small>ESPAÑOL + FUNCIÓN</small><h3>${c[1]}</h3><p>${c[2]}</p></div></button><div class="card-controls"><button id="cardAgain">↺ Necesito repasarla</button><button id="cardKnow">✓ La recuerdo</button></div></div>`;$('#studyFlashcard').onclick=()=>{cardRevealed=!cardRevealed;renderCardDeck()};$('#cardAgain').onclick=()=>{cardMastery[cardIndex]=false;localStorage.setItem('rutaCdlCardMastery',JSON.stringify(cardMastery));cardIndex=(cardIndex+1)%cardDeck.length;cardRevealed=false;renderCardDeck()};$('#cardKnow').onclick=()=>{cardMastery[cardIndex]=true;localStorage.setItem('rutaCdlCardMastery',JSON.stringify(cardMastery));cardIndex=(cardIndex+1)%cardDeck.length;cardRevealed=false;renderCardDeck()}}
cardDeck.push(['Supply pressure gauge','Medidor de presión de suministro','Shows pressure in the air tanks.'],['Application pressure gauge','Medidor de presión de aplicación','Shows air pressure applied to the brakes.'],['Spring brakes','Frenos de resorte','Apply mechanically when air pressure is lost.'],['Brake fade','Desvanecimiento de frenos','Loss of braking power caused by excessive heat.'],['Stopping distance','Distancia de parada','Perception, reaction, brake lag and braking distance combined.'],['Escape ramp','Rampa de escape','A designated path for vehicles that cannot stop on a downgrade.'],['Blind spot','Punto ciego','An area around the vehicle that mirrors do not show.'],['Offtracking','Desviación de trayectoria','Rear wheels follow a different path in a turn.'],['Emergency exit','Salida de emergencia','Must be marked, operational and securely closed.'],['Railroad crossing','Cruce ferroviario','Requires special observation and stopping procedures for buses.'],['Hazardous materials','Materiales peligrosos','Cargo regulated because it may pose unreasonable risk.'],['Pre-trip inspection','Inspección previa al viaje','Systematic verification that the vehicle is safe to operate.']);
const inspectionOrder=['Check vehicle overview','Check engine compartment','Start engine and inspect inside the cab','Turn off engine and check lights','Do walk-around inspection','Check signal lights','Start engine and check brake system'];
function renderSequenceActivity(){const shuffled=[...inspectionOrder].sort(()=>Math.random()-.5);let picks=[];$('#academyStage').innerHTML=`<div class="activity-panel"><p class="eyebrow dark"><span></span> MEMORIA DE PROCEDIMIENTO</p><h3>Construye la inspección de 7 pasos</h3><p>Selecciona cada paso en el orden correcto. Recibirás una puntuación exacta al terminar.</p><div class="sequence-list">${shuffled.map(x=>`<button class="sequence-item" data-sequence="${x}"><span>↕</span><strong>${x}</strong><small>Seleccionar</small></button>`).join('')}</div><div id="sequenceResult"></div></div>`;$$('[data-sequence]').forEach(b=>b.onclick=()=>{if(b.disabled)return;picks.push(b.dataset.sequence);b.disabled=true;b.querySelector('span').textContent=picks.length;if(picks.length===7){const score=picks.filter((x,i)=>x===inspectionOrder[i]).length;$('#sequenceResult').innerHTML=`<div class="academy-feedback"><strong>${score}/7 posiciones correctas.</strong><ol>${inspectionOrder.map(x=>`<li>${x}</li>`).join('')}</ol><button class="outline" id="retrySequence">Intentar de nuevo</button></div>`;$('#retrySequence').onclick=renderSequenceActivity}})}
const scenarios=[
 {q:'Un pasajero está de pie delante de la línea de seguridad. ¿Qué haces antes de iniciar la marcha?',a:['Iniciar lentamente.','Pedir que permanezca detrás de la línea y verificar.','Confiar en el pasamanos.'],c:1,e:'La línea debe permanecer despejada mientras el autobús está en movimiento.'},
 {q:'Llevas pasajeros y necesitas cargar combustible. ¿Dónde nunca debes hacerlo?',a:['En un edificio cerrado.','En una estación al aire libre.','Con las luces apagadas.'],c:0,e:'El manual de pasajeros prohíbe abastecer un autobús ocupado dentro de un edificio cerrado.'},
 {q:'Te aproximas a una curva con una velocidad señalada. ¿Qué debes asumir?',a:['Siempre es segura para un autobús.','Puede ser demasiado rápida para el autobús.','Debes acelerar antes de entrar.'],c:1,e:'La velocidad indicada puede ser insegura para un vehículo grande o autobús.'},
 {q:'Esperas un espacio para incorporarte al tráfico con el autobús.',a:['Esperas un espacio suficientemente grande.','Avanzas por el acotamiento.','Obligas al tráfico a reducir velocidad.'],c:0,e:'El tamaño y la aceleración del autobús requieren una brecha suficientemente amplia.'},
 {q:'Durante tu recorrido detectas una salida de emergencia abierta.',a:['Continúas si hace calor.','La aseguras antes de continuar.','Solo reduces la velocidad.'],c:1,e:'Las salidas de emergencia deben estar cerradas de forma segura durante la operación normal.'}
];
scenarios.push(
 {q:'La advertencia de baja presión se activa mientras conduces.',a:['Continúas hasta la terminal.','Te detienes de forma segura tan pronto como sea posible.','Bombeas repetidamente el pedal.'],c:1,e:'Debes detenerte de forma segura antes de que los frenos de resorte se apliquen.'},
 {q:'Vas cuesta abajo y notas pérdida de eficacia de frenado.',a:['Cambias a una marcha más baja y buscas una salida segura.','Aumentas la velocidad.','Mantienes el pedal presionado continuamente.'],c:0,e:'La marcha baja y una técnica correcta reducen calor; el frenado continuo puede causar desvanecimiento.'},
 {q:'Antes de mover el autobús, un espejo está desajustado.',a:['Lo ajustas antes de iniciar.','Compensas girando la cabeza después.','Lo revisas al final del turno.'],c:0,e:'Los espejos deben ajustarse antes de conducir.'},
 {q:'Encuentras equipaje bloqueando el pasillo.',a:['Lo dejas si el viaje es corto.','Pides que se guarde sin bloquear pasillo ni salida.','Solo reduces la velocidad.'],c:1,e:'Los pasillos y salidas deben permanecer libres.'},
 {q:'Debes girar a la derecha en una calle estrecha.',a:['Vigilas espejos y recorrido de las ruedas traseras.','Te pegas al bordillo desde muy lejos.','Ignoras el lado izquierdo.'],c:0,e:'La desviación de trayectoria exige vigilar espejos y espacio lateral.'},
 {q:'Un neumático tiene una protuberancia visible.',a:['Lo anotas para la próxima semana.','No operas hasta que se evalúe o repare.','Bajas la presión.'],c:1,e:'Una protuberancia indica daño estructural.'},
 {q:'Te aproximas a un cruce ferroviario con pasajeros.',a:['Aplicas el procedimiento requerido.','Sigues al automóvil delantero.','Cambias de marcha sobre las vías.'],c:0,e:'Los autobuses tienen procedimientos especiales y no deben cambiar de marcha sobre las vías.'}
);
let scenarioIndex=0,scenarioScore=0;
function renderScenarioActivity(){const s=scenarios[scenarioIndex];$('#academyStage').innerHTML=`<div class="activity-panel"><div class="deck-progress"><span>ESCENARIO ${scenarioIndex+1} / ${scenarios.length}</span><strong>${scenarioScore} correctos</strong></div><p class="eyebrow dark"><span></span> DECISIÓN SEGURA</p><h3>${s.q}</h3><div class="scenario-options">${s.a.map((x,i)=>`<button data-scenario-choice="${i}">${x}</button>`).join('')}</div><div id="scenarioFeedback"></div></div>`;$$('[data-scenario-choice]').forEach(b=>b.onclick=()=>{const ok=+b.dataset.scenarioChoice===s.c;if(ok)scenarioScore++;$$('[data-scenario-choice]').forEach((x,i)=>{x.disabled=true;x.classList.toggle('correct-choice',i===s.c);x.classList.toggle('wrong-choice',x===b&&!ok)});$('#scenarioFeedback').innerHTML=`<div class="academy-feedback"><strong>${ok?'Correcto.':'Revisa la decisión.'}</strong> ${s.e}<br><button class="outline" id="nextScenario">${scenarioIndex===scenarios.length-1?'Ver resultado':'Siguiente escenario →'}</button></div>`;$('#nextScenario').onclick=()=>{if(scenarioIndex===scenarios.length-1){$('#scenarioFeedback').innerHTML=`<div class="academy-feedback"><strong>Resultado: ${scenarioScore}/${scenarios.length}</strong> Los escenarios pueden repetirse para mejorar el dominio.</div>`}else{scenarioIndex++;renderScenarioActivity()}}})}
const lessonSlides=[{title:'Tres sistemas, tres funciones',body:'El sistema de servicio aplica y libera los frenos durante la conducción normal. El sistema de estacionamiento mantiene el vehículo detenido. El sistema de emergencia combina componentes para responder a una falla.'},{title:'La presión es información',body:'Los medidores, la advertencia de baja presión y el tiempo de acumulación permiten detectar problemas antes de mover el vehículo.'},{title:'Comprueba lo aprendido',body:'¿Qué sistema se usa normalmente al presionar el pedal?',options:['Servicio','Estacionamiento','Emergencia'],correct:0}];let lessonSlide=0;
function renderLesson(){const s=lessonSlides[lessonSlide];$('#academyStage').innerHTML=`<div class="activity-panel lesson-panel"><div class="deck-progress"><span>MICROLECCIÓN · ${lessonSlide+1}/${lessonSlides.length}</span><strong>Frenos de aire</strong></div><h3>${s.title}</h3><p>${s.body}</p>${s.options?`<div class="scenario-options">${s.options.map((x,i)=>`<button data-lesson-answer="${i}">${x}</button>`).join('')}</div><div id="lessonFeedback"></div>`:`<button class="primary" id="lessonNext">Continuar →</button>`}</div>`;if($('#lessonNext'))$('#lessonNext').onclick=()=>{lessonSlide++;renderLesson()};$$('[data-lesson-answer]').forEach(b=>b.onclick=()=>{$$('[data-lesson-answer]').forEach((x,i)=>x.classList.toggle('correct-choice',i===s.correct));$('#lessonFeedback').innerHTML=`<div class="academy-feedback">${+b.dataset.lessonAnswer===s.correct?'Correcto.':'La respuesta correcta es Servicio.'} <button class="outline" id="restartLesson">Repetir lección</button></div>`;$('#restartLesson').onclick=()=>{lessonSlide=0;renderLesson()}})}
const mapTopics={inspection:['Inspección','Descripción general → compartimiento del motor → cabina → luces → recorrido exterior → señales → frenos.'],space:['Gestión del espacio','Distancia de seguimiento, espacio lateral, altura libre y espacio para girar.'],brakes:['Frenos de aire','Compresor → depósitos → válvulas → cámaras → ajustadores → frenos.'],passengers:['Pasajeros','Línea para pasajeros de pie, salidas, equipaje, paradas y cruces ferroviarios.'],emergency:['Emergencias','Falla de frenos, reventón, incendio, derrape y salida de la carretera.']};
function renderKnowledgeMap(){const selected='inspection';$('#academyStage').innerHTML=`<div class="activity-panel"><p class="eyebrow dark"><span></span> MAPA DE CONOCIMIENTO</p><div class="knowledge-map">${Object.entries(mapTopics).map(([k,v])=>`<button data-map-topic="${k}">${v[0]}</button>`).join('')}<div class="map-detail" id="mapDetail"><h3>${mapTopics[selected][0]}</h3><p>${mapTopics[selected][1]}</p></div></div></div>`;$$('[data-map-topic]').forEach(b=>b.onclick=()=>{const t=mapTopics[b.dataset.mapTopic];$$('[data-map-topic]').forEach(x=>x.classList.toggle('active',x===b));$('#mapDetail').innerHTML=`<h3>${t[0]}</h3><p>${t[1]}</p>`})}
function renderAdaptivePlan(){const checked=Object.keys(state.checked).length,correct=Object.keys(state.checked).filter(i=>state.answers[i]===questions[i].correct).length,accuracy=checked?Math.round(correct/checked*100):0,mastered=Object.values(cardMastery).filter(Boolean).length,sourceTotal=Object.values(sourceAnswers).filter(x=>x&&typeof x==='object').reduce((n,x)=>n+Object.keys(x).length,0);const priority=accuracy<80?'Conocimiento general':mastered<8?'Vocabulario y frenos de aire':'Formularios completos';$('#academyStage').innerHTML=`<div class="activity-panel"><p class="eyebrow dark"><span></span> PLAN ADAPTATIVO REAL</p><h3>Prioridad: ${priority}</h3><p>Calculado con ${checked} respuestas comprobadas, ${mastered}/${cardDeck.length} tarjetas dominadas y ${sourceTotal} respuestas sobre escaneos.</p><div class="study-plan"><div class="plan-day"><b>Sesión 1 · 15 min</b><span>${accuracy<80?'Corrige preguntas falladas y lee sus explicaciones.':'Completa un formulario histórico con clave.'}</span></div><div class="plan-day"><b>Sesión 2 · 12 min</b><span>${mastered<8?'Repasa el mazo hasta dominar ocho términos.':'Resuelve los cinco escenarios de pasajeros.'}</span></div><div class="plan-day"><b>Sesión 3 · 20 min</b><span>Haz el reto de 60 segundos y busca al menos 85% de precisión.</span></div></div></div>`}
let sourceExamPage=1;const sourceAnswers=JSON.parse(localStorage.getItem('rutaCdlSourceAnswers')||'{}');
const pageForms={
1:{section:'General Knowledge / Air Brake Test',numbers:[1,2,3,4,5,6,7,8,9,10],key:{1:'A',2:'B',3:'B',4:'A',5:'C',6:'C',7:'C',8:'B',9:'B',10:'B'}},
2:{section:'General Knowledge Test',numbers:[22,23,24,25,26,27,28,29,30,31,32],key:{22:'B',23:'B',24:'C',25:'C',26:'B',27:'C',28:'C',29:'B',30:'A',31:'B',32:'C'}},3:{section:'General Knowledge Test',numbers:[43,44,45,46,47,48,49,50],key:{43:'B',44:'A',45:'C',46:'A',47:'B',48:'C',49:'C',50:'A'}},4:{section:'Air Brake Test',numbers:[14,15,16,17,18,19,20],key:{14:'C',15:'B',16:'C',17:'A',18:'A',19:'A',20:'A'}},
5:{section:'General Knowledge Test',numbers:[9,10,11,12,13,14,15,16,17,18,19,20],key:{9:'A',10:'C',11:'B',12:'C',13:'A',14:'C',15:'C',16:'B',17:'C',18:'C',19:'A',20:'B'}},6:{section:'General Knowledge Test',numbers:[33,34,35,36,37,38,39,40,41,42,43,44],key:{33:'C',34:'B',35:'A',36:'C',37:'C',38:'B',39:'A',40:'A',41:'B',42:'A',43:'A',44:'C'}},7:{section:'Air Brake Test',numbers:[3,4,5,6,7,8,9,10,11,12,13,14],key:{3:'C',4:'A',5:'B',6:'C',7:'A',8:'C',9:'C',10:'B',11:'A',12:'B',13:'A',14:'B'}},
8:{section:'General Knowledge Test',numbers:[1,2,3,4,5,6,7,8,9],key:{1:'A',2:'C',3:'B',4:'C',5:'A',6:'B',7:'C',8:'A',9:'A'}},9:{section:'General Knowledge Test',numbers:[21,22,23,24,25,26,27,28,29,30,31,32],unanswerable:[22],key:{21:'B',23:'B',24:'C',25:'C',26:'C',27:'A',28:'C',29:'B',30:'C',31:'B',32:'B'}},10:{section:'General Knowledge Test',numbers:[46,47,48,49,50],unanswerable:[47],key:{46:'B',48:'A',49:'A',50:'A'}},
11:{section:'General Knowledge Test',numbers:[11,12,13,14,15,16,17,18,19,20,21],key:{11:'C',12:'A',13:'C',14:'B',15:'A',16:'C',17:'C',18:'B',19:'C',20:'C',21:'B'}},12:{section:'General Knowledge Test',numbers:[34,35,36,37,38,39,40,41,42,43],key:{34:'C',35:'B',36:'C',37:'C',38:'A',39:'A',40:'B',41:'B',42:'B',43:'C'}},13:{section:'Air Brake Test',numbers:[5,6,7,8,9,10,11,12,13,14,15],key:{5:'A',6:'B',7:'C',8:'A',9:'A',10:'A',11:'B',12:'C',13:'A',14:'C',15:'B'}},
14:{section:'General Knowledge Test',numbers:[1,2,3,4,5,6,7,8,9,10],key:{1:'C',2:'A',3:'B',4:'C',5:'A',6:'A',7:'C',8:'C',9:'C',10:'B'}},15:{section:'General Knowledge Test',numbers:[21,22,23,24,25,26,27,28,29,30,31,32,33],key:{21:'B',22:'B',23:'C',24:'C',25:'B',26:'B',27:'C',28:'B',29:'A',30:'A',31:'A',32:'C',33:'C'}},16:{section:'General Knowledge Test',numbers:[46,47,48,49,50],key:{46:'C',47:'C',48:'A',49:'C',50:'A'}},
17:{section:'Passenger Transport Endorsement',numbers:[1,2,3,4,5,6,7,8,9,10,11],key:{1:'A',2:'C',3:'A',4:'B',5:'B',6:'C',7:'A',8:'C',9:'C',10:'C',11:'A'}},18:{section:'Passenger Transport Endorsement',numbers:[1,2,3,4,5,6,7,8,9,10],key:{1:'B',2:'A',3:'C',4:'A',5:'C',6:'B',7:'B',8:'C',9:'C',10:'B'}},19:{section:'Passenger Transport Endorsement',numbers:[1,2,3,4,5,6,7,8,9,10],key:{1:'B',2:'C',3:'A',4:'C',5:'C',6:'A',7:'C',8:'C',9:'C',10:'A'}},20:{section:'Passenger Transport Endorsement',numbers:[1,2,3,4,5,6,7,8,9,10],key:{1:'B',2:'C',3:'C',4:'C',5:'A',6:'A',7:'B',8:'C',9:'C',10:'A'}},
21:{section:'Class C Examination',numbers:[1,2,3,4,5,6,7,8,9,10],key:{1:'B',2:'B',3:'B',4:'B',5:'B',6:'A',7:'B',8:'B',9:'A',10:'A'}},22:{section:'Class C Examination',numbers:[1,2,3,4,5,6,7,8,9,10],key:{1:'B',2:'C',3:'C',4:'C',5:'A',6:'C',7:'A',8:'C',9:'A',10:'C'}},23:{section:'Commercial Driver Examination',numbers:[1,2,3,4,5,6,7,8,9],key:{1:'C',2:'A',3:'C',4:'A',5:'A',6:'B',7:'A',8:'A',9:'B'}},24:{section:'Commercial Driver Examination',numbers:[1,2,3,4,5,6,7,8,9],key:{1:'B',2:'B',3:'A',4:'A',5:'B',6:'A',7:'A',8:'C',9:'A'}},25:{section:'Commercial Driver Examination',numbers:[1,2,3,4,5,6,7,8,9],key:{1:'B',2:'B',3:'C',4:'A',5:'B',6:'A',7:'B',8:'B',9:'C'}},26:{section:'Commercial Driver Examination',numbers:[1,2,3,4,5,6,7,8,9],key:{1:'B',2:'A',3:'A',4:'B',5:'B',6:'C',7:'C',8:'B',9:'A'}}
};
const verifiedQuestionBank=Object.entries(pageForms).flatMap(([page,form])=>form.numbers.filter(number=>form.key[number]).map(number=>({page:+page,number,section:form.section,correct:form.key[number]})));
let customExam=[],customExamIndex=0,customExamAnswers={},customExamFinished=false;
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function renderExamBuilder(){customExam=[];customExamAnswers={};customExamFinished=false;$('#customExamShell').innerHTML=`<div class="exam-builder"><p class="eyebrow dark"><span></span> CONSTRUCTOR DE EXAMEN</p><h2>Elige la duración de tu simulación</h2><p>Las preguntas se seleccionan de las <strong>${verifiedQuestionBank.length} respuestas verificadas</strong> de las 26 páginas. Verás siempre la página original para responder sin alterar su contenido.</p><div class="exam-size-grid">${[10,25,50,verifiedQuestionBank.length].map(n=>`<button data-exam-size="${n}"><strong>${n}</strong><span>${n===verifiedQuestionBank.length?'Examen integral':'preguntas aleatorias'}</span></button>`).join('')}</div><label class="exam-filter">Sección <select id="examSection"><option value="all">Todas las secciones</option><option value="General">Conocimiento general</option><option value="Air Brake">Frenos de aire</option><option value="Passenger">Pasajeros</option><option value="Class C">Clase C</option><option value="Commercial Driver">Conductor comercial</option></select></label><p class="exam-note">Cada intento cambia el orden. Las respuestas quedan ocultas hasta terminar.</p></div>`;$$('[data-exam-size]').forEach(b=>b.onclick=()=>startCustomExam(+b.dataset.examSize))}
function startCustomExam(size){const filter=$('#examSection').value;const pool=filter==='all'?verifiedQuestionBank:verifiedQuestionBank.filter(q=>q.section.includes(filter));customExam=shuffle(pool).slice(0,Math.min(size,pool.length));customExamIndex=0;customExamAnswers={};customExamFinished=false;renderCustomExamQuestion()}
function renderCustomExamQuestion(){const q=customExam[customExamIndex],answer=customExamAnswers[customExamIndex],answered=Object.keys(customExamAnswers).length;if(!q)return renderExamBuilder();$('#customExamShell').innerHTML=`<div class="custom-exam-head"><div><small>SIMULACIÓN PERSONALIZADA</small><strong>${customExamIndex+1} / ${customExam.length}</strong></div><div class="custom-progress"><i style="width:${(customExamIndex+1)/customExam.length*100}%"></i></div><span>${answered} respondidas</span></div><div class="custom-exam-body"><article><header><strong>Página ${q.page} · Pregunta ${q.number}</strong><small>${q.section} · documento original</small></header><div><img src="assets/questionnaire/page-${String(q.page).padStart(2,'0')}.jpg" alt="Página ${q.page} del cuestionario original"></div></article><aside><p class="eyebrow dark"><span></span> TU RESPUESTA</p><h3>Localiza la pregunta ${q.number} en el original.</h3><p>Selecciona una opción. La clave permanecerá oculta hasta entregar el examen.</p><div class="custom-answer-options">${['A','B','C'].map(letter=>`<button class="${answer===letter?'selected':''}" data-custom-answer="${letter}">${letter}</button>`).join('')}</div><div class="custom-navigation"><button id="customPrev" ${customExamIndex===0?'disabled':''}>← Anterior</button><button id="customNext">${customExamIndex===customExam.length-1?'Revisar y entregar':'Siguiente →'}</button></div><button class="exam-exit" id="customExit">Salir y crear otro examen</button></aside></div>`;$$('[data-custom-answer]').forEach(b=>b.onclick=()=>{customExamAnswers[customExamIndex]=b.dataset.customAnswer;renderCustomExamQuestion()});$('#customPrev').onclick=()=>{customExamIndex--;renderCustomExamQuestion()};$('#customNext').onclick=()=>{if(customExamIndex===customExam.length-1)renderCustomExamReview();else{customExamIndex++;renderCustomExamQuestion()}};$('#customExit').onclick=renderExamBuilder}
function renderCustomExamReview(){const unanswered=customExam.length-Object.keys(customExamAnswers).length;$('#customExamShell').innerHTML=`<div class="exam-review"><p class="eyebrow dark"><span></span> REVISIÓN ANTES DE ENTREGAR</p><h2>${unanswered?`${unanswered} sin responder`:'Todo listo'}</h2><p>Puedes regresar a cualquier pregunta o entregar para revelar la clave.</p><div class="review-map">${customExam.map((q,i)=>`<button class="${customExamAnswers[i]?'answered':''}" data-review-jump="${i}">${i+1}</button>`).join('')}</div><div class="review-actions"><button id="reviewBack">← Continuar respondiendo</button><button class="grade-source" id="submitCustomExam">Entregar y calificar</button></div></div>`;$$('[data-review-jump]').forEach(b=>b.onclick=()=>{customExamIndex=+b.dataset.reviewJump;renderCustomExamQuestion()});$('#reviewBack').onclick=()=>renderCustomExamQuestion();$('#submitCustomExam').onclick=finishCustomExam}
function finishCustomExam(){customExamFinished=true;const score=customExam.filter((q,i)=>customExamAnswers[i]===q.correct).length,percent=Math.round(score/customExam.length*100);const history=JSON.parse(localStorage.getItem('rutaCdlExamHistory')||'[]');history.unshift({date:new Date().toISOString(),size:customExam.length,score,percent});localStorage.setItem('rutaCdlExamHistory',JSON.stringify(history.slice(0,20)));$('#customExamShell').innerHTML=`<div class="exam-results"><div class="result-ring"><strong>${percent}%</strong><span>${score}/${customExam.length}</span></div><div><p class="eyebrow dark"><span></span> RESULTADO FINAL</p><h2>${percent>=80?'Nivel de aprobación':'Sigue practicando'}</h2><p>${customExam.length-score} respuestas requieren revisión. Selecciona una para volver a la página fuente y comparar la clave.</p><div class="mistake-list">${customExam.map((q,i)=>({q,i})).filter(x=>customExamAnswers[x.i]!==x.q.correct).map(({q,i})=>`<button data-result-jump="${i}"><span>Pág. ${q.page} · #${q.number}</span><b>${customExamAnswers[i]||'—'} → ${q.correct}</b></button>`).join('')||'<strong>¡No hubo errores!</strong>'}</div><button class="grade-source" id="newCustomExam">Crear otro examen</button></div></div>`;$$('[data-result-jump]').forEach(b=>b.onclick=()=>{customExamIndex=+b.dataset.resultJump;renderCustomExamQuestion();const q=customExam[customExamIndex];setTimeout(()=>{const aside=$('#customExamShell aside');if(aside)aside.insertAdjacentHTML('afterbegin',`<div class="result-correction">Tu respuesta: <b>${customExamAnswers[customExamIndex]||'—'}</b> · Clave: <b>${q.correct}</b></div>`)},0)});$('#newCustomExam').onclick=renderExamBuilder;updateStats()}
function renderSourceExam(){const pageKey=`p${sourceExamPage}`,form=pageForms[sourceExamPage],answers=sourceAnswers[pageKey]||{},key=form.key||{},graded=sourceAnswers[`${pageKey}Graded`],answered=form.numbers.filter(n=>answers[n]).length,score=form.numbers.filter(n=>key[n]&&answers[n]===key[n]).length,keyCount=Object.keys(key).length;$('#sourceExamShell').innerHTML=`<div class="source-exam-head"><div><strong>${form.section} · Página ${sourceExamPage}</strong><small>${form.numbers.length} preguntas visibles · números ${form.numbers[0]}–${form.numbers.at(-1)} según el formulario original</small></div><div><button id="sourceExamPrev">←</button><span>${String(sourceExamPage).padStart(2,'0')} / 26</span><button id="sourceExamNext">→</button></div></div><div class="source-exam-body"><div class="source-exam-page"><img src="assets/questionnaire/page-${String(sourceExamPage).padStart(2,'0')}.jpg" alt="Página ${sourceExamPage} original"></div><aside class="answer-sheet"><p class="eyebrow dark"><span></span> HOJA DE RESPUESTAS REAL</p><h3>${form.section}</h3><p>Solo aparecen los números impresos en esta página. Los saltos se conservan tal como vienen en el PDF.</p><div class="answer-sheet-grid">${form.numbers.map(n=>`<div class="answer-row ${graded&&key[n]?(answers[n]===key[n]?'row-correct':'row-wrong'):''}"><span>${n}</span>${['A','B','C'].map(letter=>`<button class="${answers[n]===letter?'selected':''} ${graded&&key[n]===letter?'key-answer':''}" data-source-answer="${n}" data-source-letter="${letter}">${letter}</button>`).join('')}</div>`).join('')}</div><div class="source-answer-progress"><strong>${answered}/${form.numbers.length}</strong> respondidas · <strong>${keyCount}/${form.numbers.length}</strong> respuestas verificadas</div>${keyCount?`<button class="grade-source" id="gradeSource">${graded?'Ocultar revisión':'Revisar respuestas verificadas'}</button>`:'<div class="key-pending">Clave en verificación contra el manual. Tus respuestas se guardan, pero todavía no se califican.</div>'}${graded?`<div class="source-score"><strong>${score}/${keyCount}</strong><span>correctas entre las respuestas con clave verificada</span></div>`:''}</aside></div>`;$('#sourceExamPrev').onclick=()=>{sourceExamPage=Math.max(1,sourceExamPage-1);renderSourceExam()};$('#sourceExamNext').onclick=()=>{sourceExamPage=Math.min(26,sourceExamPage+1);renderSourceExam()};$$('[data-source-answer]').forEach(b=>b.onclick=()=>{sourceAnswers[pageKey]??={};sourceAnswers[pageKey][b.dataset.sourceAnswer]=b.dataset.sourceLetter;sourceAnswers[`${pageKey}Graded`]=false;localStorage.setItem('rutaCdlSourceAnswers',JSON.stringify(sourceAnswers));renderSourceExam()});if($('#gradeSource'))$('#gradeSource').onclick=()=>{sourceAnswers[`${pageKey}Graded`]=!graded;localStorage.setItem('rutaCdlSourceAnswers',JSON.stringify(sourceAnswers));renderSourceExam()}}
const finishCustomExamBase=finishCustomExam;finishCustomExam=()=>{markActivity();finishCustomExamBase()};
const renderSourceExamBase=renderSourceExam;
renderSourceExam=()=>{
 renderSourceExamBase();
 const totalAnswered=Object.entries(pageForms).reduce((sum,[page,form])=>sum+form.numbers.filter(number=>(sourceAnswers[`p${page}`]||{})[number]).length,0);
 const nav=$('.source-exam-head>div:last-child');
 nav.insertAdjacentHTML('afterbegin',`<label class="source-page-jump">Ir a <select id="sourcePageJump">${Object.keys(pageForms).map(page=>`<option value="${page}" ${+page===sourceExamPage?'selected':''}>Pág. ${page}</option>`).join('')}</select></label>`);
 $('#sourcePageJump').onchange=event=>{sourceExamPage=+event.target.value;renderSourceExam()};
 $('.answer-sheet').insertAdjacentHTML('afterbegin',`<div class="global-source-progress"><span>PROGRESO GLOBAL</span><strong>${totalAnswered} / 255</strong><i><em style="width:${Math.round(totalAnswered/255*100)}%"></em></i><small>Las numeraciones se repiten porque son formularios distintos; el progreso reúne las 26 páginas.</small></div>`);
 $$('[data-source-answer]').forEach(button=>button.addEventListener('click',markActivity,{once:true}));
 (pageForms[sourceExamPage].unanswerable||[]).forEach(number=>$$(`[data-source-answer="${number}"]`).forEach(button=>{button.disabled=true;button.title='El original muestra ?? y no incluye opciones'}));
 updateStats();
};
function openAnswerKey(){const rows=Object.entries(pageForms).map(([page,form])=>`<section><h2>Página ${page} · ${form.section}</h2><div class="answers">${form.numbers.map(n=>`<span><b>${n}</b>${form.unanswerable?.includes(n)?'—':form.key[n]}</span>`).join('')}</div></section>`).join('');const win=open('','_blank');win.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Clave completa · Ruta CDL</title><style>body{font:14px Arial;margin:40px;color:#102637}header{border-bottom:4px solid #f4b941;padding-bottom:20px}h1{margin:0}p{color:#60717d}section{break-inside:avoid;border-bottom:1px solid #ddd;padding:15px 0}h2{font-size:15px}.answers{display:flex;flex-wrap:wrap;gap:7px}.answers span{border:1px solid #bcc8ce;border-radius:5px;padding:7px 10px}.answers b{margin-right:8px;color:#2463a9}@media print{button{display:none}}</style></head><body><header><h1>Clave del cuestionario histórico</h1><p>Fuente: “Cuestionario impreso - Ingles.pdf”, basado en el Manual Comercial 2003. Esta clave sirve para estudiar el formulario histórico; el manual vigente tiene prioridad.</p><button onclick="print()">Imprimir / guardar PDF</button></header>${rows}<p><b>—</b> significa que el original imprime “??” y no proporciona una pregunta ni opciones.</p></body></html>`);win.document.close()}
function showAcademy(mode){
 if(mode==='reader'){$('#bilingue').scrollIntoView({behavior:'smooth'});return}
 if(mode==='lesson')renderLesson();
 if(mode==='map')renderKnowledgeMap();
 if(mode==='sequence')renderSequenceActivity();
 if(mode==='scenario')renderScenarioActivity();
 if(mode==='cards')renderCardDeck();
 if(mode==='audio'){$('#academyStage').innerHTML=`<div class="activity-panel"><p class="eyebrow dark"><span></span> VOCABULARIO TÉCNICO</p><h3>Escucha, pronuncia, conecta</h3>${pairs.map(p=>`<div class="vocab-row"><div><strong>${p[0]}</strong><small>${p[1]}</small></div><button data-speak="${p[0]}" aria-label="Escuchar ${p[0]}">▶</button></div>`).join('')}</div>`;$$('[data-speak]').forEach(b=>b.onclick=()=>{speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(b.dataset.speak))})}
 if(mode==='plan')renderAdaptivePlan();
 $('#academyStage').scrollIntoView({behavior:'smooth',block:'center'});
}
function renderScanRail(){
  $('#thumbnailRail').innerHTML=Array.from({length:26},(_,i)=>`<button class="scan-thumb ${i+1===scanPage?'active':''}" data-scan="${i+1}"><img loading="lazy" src="assets/questionnaire/page-${String(i+1).padStart(2,'0')}.jpg" alt="Miniatura de la página ${i+1}"><span>${String(i+1).padStart(2,'0')}</span></button>`).join('');
  $$('[data-scan]').forEach(b=>b.onclick=()=>selectScan(+b.dataset.scan));
}
function selectScan(page){scanPage=Math.max(1,Math.min(26,page));const code=String(scanPage).padStart(2,'0');$('#scanImage').src=`assets/questionnaire/page-${code}.jpg`;$('#scanImage').alt=`Página ${scanPage} del cuestionario original`;$('#scanTitle').textContent=`Página ${scanPage}`;$('#scanCount').textContent=`${code} / 26`;$('#notesPage').textContent=scanPage;$('#notesInput').value=localStorage.getItem(`rutaCdlNote${scanPage}`)||'';renderScanRail();const active=$(`[data-scan="${scanPage}"]`);if(active)active.scrollIntoView({block:'nearest'})}
function setZoom(delta){scanZoom=Math.max(35,Math.min(140,scanZoom+delta));$('#scanImage').style.width=`${scanZoom}%`;$('#zoomLabel').textContent=`${scanZoom}%`}
const compareDocuments={commercial:{en:'DL-650-2019-2021-Aug-2023-passes-accessibility.pdf',es:'Commercial-Driver-Handbook-Spanish-Official.pdf',enTitle:'Commercial Driver Handbook',esTitle:'Manual del Conductor Comercial',note:'<strong>Correspondencia completa disponible.</strong> Ambas publicaciones contienen 208 páginas y conservan la estructura del Manual del Conductor Comercial.'},general:{en:'8-11-25-DL-600-R6-2025-WWW.pdf',es:'California-Driver-Handbook-2025-Spanish-Official.pdf',enTitle:"California Driver’s Handbook",esTitle:'Resumen del Manual del Automovilista',note:'<strong>Publicación oficial no equivalente página por página.</strong> El DMV ofrece la edición española como un resumen de 68 páginas frente a las 92 páginas de la edición inglesa.'}};
function selectComparison(key){const d=compareDocuments[key];$$('[data-compare]').forEach(b=>b.classList.toggle('active',b.dataset.compare===key));$('#compareEnglish').data=encodeURI(d.en);$('#compareSpanish').data=encodeURI(d.es);$('#compareEnglishTitle').textContent=d.enTitle;$('#compareSpanishTitle').textContent=d.esTitle;$('#compareEnglishOpen').href=d.en;$('#compareSpanishOpen').href=d.es;$('#compareNote').innerHTML=d.note}
$('#scanPrev').onclick=()=>selectScan(scanPage-1);$('#scanNext').onclick=()=>selectScan(scanPage+1);$('#zoomIn').onclick=()=>setZoom(10);$('#zoomOut').onclick=()=>setZoom(-10);$('#scanFullscreen').onclick=()=>$('.scan-workspace').classList.toggle('focus-mode');$$('[data-tool]').forEach(b=>b.onclick=()=>{const tool=b.dataset.tool;if(tool==='focus')$('.scan-workspace').classList.toggle('focus-mode');if(tool==='notes')$('#pageNotes').hidden=!$('#pageNotes').hidden;if(tool==='practice'){$('#practica').scrollIntoView({behavior:'smooth'});showPractice('quiz')}});$('#notesInput').oninput=e=>localStorage.setItem(`rutaCdlNote${scanPage}`,e.target.value);$$('[data-compare]').forEach(b=>b.onclick=()=>selectComparison(b.dataset.compare));selectComparison('commercial');
let translationPage=1,translationFont=15,translationText='';
$('#translationPageSelect').innerHTML=Array.from({length:26},(_,i)=>`<option value="${i+1}">Página ${i+1}</option>`).join('');
function escapeHtml(value){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function paintTranslation(){const query=$('#translationSearch').value.trim();let safe=escapeHtml(translationText);if(query){const escaped=query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');safe=safe.replace(new RegExp(escaped,'gi'),m=>`<mark>${m}</mark>`)}$('#translatedPage').innerHTML=safe||'<p>No fue posible cargar esta página.</p>';$('#translatedPage').style.fontSize=`${translationFont}px`;const first=$('#translatedPage mark');if(first)first.scrollIntoView({block:'center'})}
function selectTranslationPage(page){translationPage=Math.max(1,Math.min(26,+page));const code=String(translationPage).padStart(2,'0');$('#translationPageCount').textContent=`${code} / 26`;$('#translationSourcePage').textContent=translationPage;$('#translationPageSelect').value=translationPage;$('#translationSourceImage').src=`assets/questionnaire/page-${code}.jpg`;$('#translationSourceImage').alt=`Página ${translationPage} del cuestionario original en inglés`;translationText=(window.QUESTIONNAIRE_SPANISH||{})[code]||'Traducción no disponible.';paintTranslation()}
$('#translationPrev').onclick=()=>selectTranslationPage(translationPage-1);$('#translationNext').onclick=()=>selectTranslationPage(translationPage+1);$('#translationPageSelect').onchange=e=>selectTranslationPage(e.target.value);$('#translationSearch').oninput=paintTranslation;$('#translationSmaller').onclick=()=>{translationFont=Math.max(11,translationFont-1);paintTranslation()};$('#translationLarger').onclick=()=>{translationFont=Math.min(24,translationFont+1);paintTranslation()};selectTranslationPage(1);
$('#languageButton').addEventListener('click',e=>{e.stopImmediatePropagation();const d=documents[currentDocument];if(!d.spanishFile){$('#traduccion').scrollIntoView({behavior:'smooth'});return}currentDocLanguage=currentDocLanguage==='en'?'es':'en';selectDocument(currentDocument)},true);
$('#clearProgress').addEventListener('click',e=>{e.stopImmediatePropagation();if(confirm('¿Borrar respuestas, notas, tarjetas y todo el progreso guardado en este navegador?')){Object.keys(localStorage).filter(k=>k.startsWith('rutaCdl')).forEach(k=>localStorage.removeItem(k));location.reload()}},true);
$('#answerKeyButton').onclick=openAnswerKey;
renderDocuments();renderQuestion();updateStats();renderScanRail();
const startupMode=new URLSearchParams(location.search).get('mode');showPractice(['quiz','source','custom','match','rapid'].includes(startupMode)?startupMode:'source');
$('#translateToggle').onclick=()=>{const p=$('#questionTranslation');p.hidden=!p.hidden;$('#translateToggle').textContent=p.hidden?'Ver apoyo en español':'Ocultar apoyo en español'};$('#checkAnswer').onclick=checkAnswer;$('#prevQuestion').onclick=()=>{current=(current+questions.length-1)%questions.length;renderQuestion()};$('#nextQuestion').onclick=()=>{current=(current+1)%questions.length;renderQuestion()};$('#resetQuiz').onclick=()=>{state.answers={};state.checked={};current=0;save();renderQuestion()};$$('[data-practice]').forEach(b=>b.onclick=()=>showPractice(b.dataset.practice));$$('[data-mode]').forEach(b=>b.onclick=()=>showAcademy(b.dataset.mode));$$('[data-jump]').forEach(b=>b.onclick=()=>{if(b.dataset.jump==='match')showPractice('match');$('#practica').scrollIntoView({behavior:'smooth'})});$('#noticeClose').onclick=()=>$('.source-notice').remove();$('#clearProgress').onclick=()=>{if(confirm('¿Borrar todo el progreso guardado en este navegador?')){localStorage.removeItem('rutaCdlProgress');localStorage.removeItem('rutaCdlBest');location.reload()}};$('#languageButton').onclick=()=>alert('El original siempre permanece en inglés. Usa “Ver apoyo en español” dentro de las actividades para alternar la capa de traducción.');
